language: node_js
node_js:
  - "iojs"
  - "6"
env:
  - CXX=g++-4.8

before_script: chmod 0777 ./node_modules/.bin/mocha

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8